# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai-star-wars-classifier-toy',
                'doc_host': 'https://atorma.github.io',
                'git_url': 'https://github.com/atorma/fastai-star-wars-classifier-toy',
                'lib_path': 'fastai_star_wars_classifier_toy'},
  'syms': { 'fastai_star_wars_classifier_toy.core': { 'fastai_star_wars_classifier_toy.core.foo': ( 'core.html#foo',
                                                                                                    'fastai_star_wars_classifier_toy/core.py')}}}
